# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following_user',
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ManyToManyField(related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
