# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20171020_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(default='/media/default-profile.jpg', upload_to='user'),
        ),
    ]
