# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20171020_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(default='/media/default-profile.jpg', upload_to='user', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ManyToManyField(null=True, related_name='following_user', to=settings.AUTH_USER_MODEL, verbose_name='이 유저를 팔로우하는 유저'),
        ),
    ]
