# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20171020_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_user', to=settings.AUTH_USER_MODEL, verbose_name='이 유저를 팔로우하는 유저'),
        ),
    ]
