# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20171023_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following_user',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_user',
            field=models.ManyToManyField(blank=True, related_name='followers', through='member.Relationship', to=settings.AUTH_USER_MODEL, verbose_name='팔로우 유저'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
