# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20171023_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
