# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_auto_20171023_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='block',
            new_name='relation_type',
        ),
    ]
