# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_auto_20171023_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('d', 'Django'), ('f', 'Facebook')], default='d', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relation_type',
            field=models.CharField(choices=[('Block', 'Block'), ('Close', 'Close'), ('Acquaintance', 'Acquaintance')], max_length=20),
        ),
    ]
