# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_auto_20171024_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, default='/default-profile.png', upload_to='user', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('d', 'Django'), ('f', 'Facebook')], max_length=1),
        ),
    ]
